language: node_js
node_js:
  - "5.1"
sudo: required
script: make publish

services:
  - docker

deploy:
  provider: pages
  skip_cleanup: true

env:
  global:
  - GH_REF: github.com/tshm/hundredGrids.git
